version: '3'
services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./website/data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123

  nginx:
    links:
     - mysql
    build: .
    volumes:
      - ./website:/var/www/html
    ports:
      - "7676:80"
